### ISSUE TITLE
Exchange about parsing and working with JSON

### ISSUE THREAD

**Issue by jbee** [arkanovicz/essential-json#2]
Hi!

It is always nice to see people building their own solution that actually fits the problem they have. 
I tend to do the same, especially when it comes to parsers and data structures. 

I had requirements quite similar to yours, so I built https://github.com/dhis2/json-tree . 
It started quite simple, like essential-json, and over the years I had more and more use cases, so it got extended with more features, but in its core, it is still very light weight.

I had a quick look at your implementation. It reminded me of some JSON parsers I wrote in the past. 

I just wanted to reach out in case there is any interest in taking about parsing and processing JSON.
Happy to have a chat and share experiences.

Greetings,
Jan

**Comment by arkanovicz** [comment]
Thanks for reaching out!

Well, I'm sure I can find interesting ideas if I investigate your implementation.

However, you chose to wrap leaf values in JsonValue objects, and this design choice - which is one of the main reasons why I wrote this library - makes our libraries fundamentally different.

Most if not all JSON libraries make this choice of wrapping the values. Honestly, I'm still wondering why. What benefit does it bring to have those JsonValue objects in the way of getting the values?

By the way, I'm now mostly using https://github.com/arkanovicz/essential-kson which is the same implementation but in multiplatform kotlin, and handles mutability.

Best,
  Claude

**Comment by jbee** [comment]
> However, you chose to wrap leaf values in JsonValue objects, and this design choice - which is one of the main reasons why I wrote this library - makes our libraries fundamentally different.

`JsonValue` is a virtual layer on top of `JsonNode` API which is more like the level you implemented. If you look at 
https://github.com/dhis2/json-tree/blob/main/src/main/java/org/hisp/dhis/jsontree/JsonNode.java#L387 you see that you get access to a `String` for JSON string, a `Boolean` for JSON boolean and so on. 

While in `JsonNode` there is an object for the node this is not a value wrapper. It is a "pointer" into the parser as the parsing is lazy and as such will pause and resume based on the actual usage. 

The benefit of the `JsonValue` API is data modelling and convenience for virtually no costs as all this is are "pointers" again. They are very cheap temporary objects. They also give you a place to annotate validation to model contracts and so on. So higher level usage cases. Both APIs also behave very different when it comes to existence and types. In `JsonValue` you never get errors until you actually access leaves (as, again, you work in a virtual tree that can be anything you like). In `JsonNode` usage is actually related to the input and so any access of non existing nodes or type mismatch is an error. This has proven super handy to code your processing without much checking or try-catch yet have errors where it counts.

If you just want pure parsing it is possible to use the `JsonNode` API. If you look in the implementation `JsonTree` there is code similar to your parser. At some point this was also using lists and maps for arrays and objects but over time that got made lazy as well so now it is all streams/iterators instead.

I have been doing some Java to kotlin as well but I have to say that the code looks nice but it does not perform as well and it is not as easy to work on. So I would only use it where I need it for some reason.

**Comment by jbee** [comment]
I forgot, I wanted to ask, you mentioned performance as a reason to create your own solution. 
Have you tested it compared to popular JSON libraries?

**Comment by arkanovicz** [comment]
Those intermediary objects, should they be wrappers or "pointers" as you call it, *do* get in the way: you cannot expect standard getters to directly return the value. So, sorry but your library does not fit my needs.

And you don't seem to understand the kotlin ecosystem very well.

Your only real interest here seems to be to promote your library and your lazy parsing idea.

**Comment by jbee** [comment]
> So, sorry but your library does not fit my needs.

I never tried to convince you of anything. Just explained what you are looking at. 

> You're only real interest here seems to be to promote your library and your lazy parsing idea.

It is a fair bit of code and the the laziness makes it harder to read so I explained a bit. 
This was about exchanging ideas and findings. Anyhow, suit yourself.
